### ISSUE TITLE
Failed to scrape !!!

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [nuhmanpk/PriceTrackerBot#1]
![Screenshot_2023-12-28-00-49-03-666_org telegram plus](https://github.com/nuhmanpk/PriceTrackerBot/assets/91468485/a46e731e-23fa-4ed3-bec1-95e698ce6b38)

No connection adapters were found for '/product https://dl.flipkart.com/s/uzrO0jNNNN'

**Comment by nuhmanpk** [comment]
@Ashrafmdmatin41 Are you sure that you whitelisted your ip address in mongodb . Add 0.0.0.0 to whitelist all ip by default.

**Comment by Ashrafmdmatin41** [comment]
> @Ashrafmdmatin41 Are you sure that you whitelisted your ip address in mongodb . Add 0.0.0.0 to whitelist all ip by default.

Yes brother because my same db url are allready working another bot

**Comment by nuhmanpk** [comment]
Fixed this Issue in new Update
